### ISSUE TITLE
Non-scientific floating point numbers not supported

### ISSUE THREAD

**Issue by bpawlik** [garrisonhh/ghh_json#3]
Hi,

Thanks for this great library! I noticed that non-scientific floating point numbers are not supported, i.e. they are parsed into completely wrong numbers which was hard to debug :)

E.g. this works: 1e-3 but this doesn't: 0.001, it actually outputs 0.1.

I propose to simplify `json_expect_number` to this code:
```
#include <stdlib.h>. // for strtod
...
static double json_expect_number(json_ctx_t *ctx) {
    // Convert string to double
    double num = strtod(&ctx->text[ctx->index], NULL);

    // Move pointer until not a comma and not end of line
    while (ctx->text[ctx->index] != ',' && ctx->text[ctx->index] != '\n' && ctx->text[ctx->index] != ']') {
        ctx->index++;
    }

    return num;
}
```
    
Works well this way with both scientific and regular notation.

Cheers,
Bartek

**Comment by garrisonhh** [comment]
Hi Bartek, the issue should be fixed with the latest commit. My parsing algorithm for the fractional component of floats was ignoring leading zeroes, which works great for the integral component but caused this bug. I need to write some better tests!

I would consider using `strtod`, but if I understand it correctly, when it encounters an invalid number it simply returns `0.0`. If you haven't run into it on accident, ghh_json tries to provide reasonably helpful error messages when it encounters something it's confused by. The JSON spec for numbers is also slightly different from the C spec, which isn't a huge deal but I'd like to conform pretty closely if I can.

What do you think?

**Comment by garrisonhh** [comment]
Also thanks so much for taking the time not only to use, but to dig around in the guts of my library, and bring me the source of the bug directly! I'm going to go ahead and close this for now, let me know if any more issues arise.

**Comment by bpawlik** [comment]
You're correct about strtod. I haven't tried your fix yet, but if it does work then indeed I'd prefer to use the version which can raise alert on syntax error.

Thanks again and keep up great work!
